# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ed70c986161896eaa0fab7932c4b33109bca6120d9fcfd6dea9ad77a7abbf0181ca9e7db4a119851457b7e0305f002b88a05e95c7056036392d7ba9a37bc7be

test:
  secret_key_base: 061b7c2cf11dfd937e03b5080b57a66f7c3523b3b04a9734f245018b80200dcb4784bf9852e8a8ef086f37a00ac67602312a220f6069b5f4e15f9e6dc9b9f5c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
